[package]
name = "vagabond-server"
version = "0.1.0"
authors = ["Trevor Crow"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
