name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Basic Client
      run: cargo build --verbose --bin basic-client
    - name: Build Server
      run: cargo build --verbose --bin server
    - name: Build Client
      run: cargo build --verbose --bin client
    - name: Run tests
      run: cargo test --verbose
